export interface PermissionItem {
  id: string;
  page: 'Dashboard' | 'All Letters' | 'Letter Details' | 'Encode Letter' | 'Live Search' | 'Settings';
  name: string;
  description: string;
  targetType: 'button' | 'action_icon' | 'feature' | 'system';
  defaultAdmin: boolean;
  defaultUser: boolean;
}

export const ALL_PERMISSIONS: PermissionItem[] = [
  // Dashboard Page
  {
    id: 'dashboard_add_letter',
    page: 'Dashboard',
    name: 'Add Letter Button',
    description: 'Header action button to navigate directly to letter encoding.',
    targetType: 'button',
    defaultAdmin: true,
    defaultUser: true,
  },
  {
    id: 'dashboard_track',
    page: 'Dashboard',
    name: 'Track Progress Action',
    description: 'Activity icon in recent letters table opening the 5-stage tracking drawer.',
    targetType: 'action_icon',
    defaultAdmin: true,
    defaultUser: true,
  },
  {
    id: 'dashboard_view',
    page: 'Dashboard',
    name: 'View Document Action',
    description: 'Eye icon in recent letters table linking to full document view.',
    targetType: 'action_icon',
    defaultAdmin: true,
    defaultUser: true,
  },
  {
    id: 'dashboard_edit',
    page: 'Dashboard',
    name: 'Edit Letter Action',
    description: 'Pencil icon in recent letters table opening quick editor modal.',
    targetType: 'action_icon',
    defaultAdmin: true,
    defaultUser: true,
  },
  {
    id: 'dashboard_download',
    page: 'Dashboard',
    name: 'Download PDF Action',
    description: 'Download icon in recent letters table to retrieve original file scan.',
    targetType: 'action_icon',
    defaultAdmin: true,
    defaultUser: true,
  },
  {
    id: 'dashboard_delete',
    page: 'Dashboard',
    name: 'Delete Letter Action',
    description: 'Trash icon in action menu to permanently remove recent correspondence.',
    targetType: 'action_icon',
    defaultAdmin: true,
    defaultUser: false,
  },
  {
    id: 'dashboard_refresh',
    page: 'Dashboard',
    name: 'Refresh Stats Button',
    description: 'Top button to manually reload SLA metrics and recent activity counters.',
    targetType: 'button',
    defaultAdmin: true,
    defaultUser: true,
  },

  // All Letters Page
  {
    id: 'letters_add_letter',
    page: 'All Letters',
    name: 'Add Letter Button',
    description: 'Header action button to encode incoming or outgoing correspondence.',
    targetType: 'button',
    defaultAdmin: true,
    defaultUser: true,
  },
  {
    id: 'letters_track',
    page: 'All Letters',
    name: 'Track Progress Action',
    description: 'Action menu button opening lateral tracking stepper drawer.',
    targetType: 'action_icon',
    defaultAdmin: true,
    defaultUser: true,
  },
  {
    id: 'letters_view',
    page: 'All Letters',
    name: 'View Details Action',
    description: 'Action menu button navigating to document detail inspection.',
    targetType: 'action_icon',
    defaultAdmin: true,
    defaultUser: true,
  },
  {
    id: 'letters_edit',
    page: 'All Letters',
    name: 'Edit Details Action',
    description: 'Action menu button opening metadata and SLA due date editor.',
    targetType: 'action_icon',
    defaultAdmin: true,
    defaultUser: true,
  },
  {
    id: 'letters_download',
    page: 'All Letters',
    name: 'Download PDF Action',
    description: 'Action menu button to stream or save the original scanned document.',
    targetType: 'action_icon',
    defaultAdmin: true,
    defaultUser: true,
  },
  {
    id: 'letters_sticker',
    page: 'All Letters',
    name: 'Sticker & Routing Slip Action',
    description: 'Action menu button to generate QR sticker labels or official routing slips.',
    targetType: 'action_icon',
    defaultAdmin: true,
    defaultUser: true,
  },
  {
    id: 'letters_delete',
    page: 'All Letters',
    name: 'Delete Letter Action',
    description: 'Action menu button to delete letter record and file attachments.',
    targetType: 'action_icon',
    defaultAdmin: true,
    defaultUser: false,
  },
  {
    id: 'letters_filter',
    page: 'All Letters',
    name: 'Search & Filters Bar',
    description: 'Multi-parameter filtering by type, status, priority, OCR status, and overdue toggle.',
    targetType: 'feature',
    defaultAdmin: true,
    defaultUser: true,
  },

  // Letter Details Page
  {
    id: 'detail_track',
    page: 'Letter Details',
    name: 'Track Progress Button',
    description: 'Top toolbar button opening lateral tracking drawer.',
    targetType: 'button',
    defaultAdmin: true,
    defaultUser: true,
  },
  {
    id: 'detail_sticker',
    page: 'Letter Details',
    name: 'Sticker & Slip Generator Button',
    description: 'Top toolbar button to generate vector QR stickers and printable transmittal slips.',
    targetType: 'button',
    defaultAdmin: true,
    defaultUser: true,
  },
  {
    id: 'detail_download',
    page: 'Letter Details',
    name: 'Download Document Button',
    description: 'Top toolbar button to download original scanned file.',
    targetType: 'button',
    defaultAdmin: true,
    defaultUser: true,
  },
  {
    id: 'detail_edit',
    page: 'Letter Details',
    name: 'Edit Letter Button',
    description: 'Top toolbar button opening modal to modify metadata and dates.',
    targetType: 'button',
    defaultAdmin: true,
    defaultUser: true,
  },
  {
    id: 'detail_delete',
    page: 'Letter Details',
    name: 'Delete Letter Button',
    description: 'Top toolbar button to permanently delete the document record.',
    targetType: 'button',
    defaultAdmin: true,
    defaultUser: false,
  },
  {
    id: 'detail_status_change',
    page: 'Letter Details',
    name: 'Workflow Status Selector',
    description: 'Interactive status dropdown (Received, Draft, In Review, Completed, Archived).',
    targetType: 'feature',
    defaultAdmin: true,
    defaultUser: true,
  },
  {
    id: 'detail_viewer_controls',
    page: 'Letter Details',
    name: 'Document Zoom & Rotate Controls',
    description: 'In-browser controls to zoom in/out, reset zoom, and rotate scanned documents.',
    targetType: 'button',
    defaultAdmin: true,
    defaultUser: true,
  },
  {
    id: 'detail_copy_ocr',
    page: 'Letter Details',
    name: 'Copy OCR Text Button',
    description: 'Button in text panel to copy extracted transcription to clipboard.',
    targetType: 'button',
    defaultAdmin: true,
    defaultUser: true,
  },
  {
    id: 'detail_rerun_ocr',
    page: 'Letter Details',
    name: 'Re-run OCR Reading Button',
    description: 'Button to trigger background re-reading of document scans.',
    targetType: 'button',
    defaultAdmin: true,
    defaultUser: true,
  },

  // Encode Letter Page
  {
    id: 'encode_submit',
    page: 'Encode Letter',
    name: 'Save & Submit Button',
    description: 'Final submission button registering letter and initiating OCR processing.',
    targetType: 'button',
    defaultAdmin: true,
    defaultUser: true,
  },
  {
    id: 'encode_file_upload',
    page: 'Encode Letter',
    name: 'File Upload Drag & Drop',
    description: 'Document attachment upload zone for PDFs, JPGs, and PNGs.',
    targetType: 'feature',
    defaultAdmin: true,
    defaultUser: true,
  },
  {
    id: 'encode_custom_vem',
    page: 'Encode Letter',
    name: 'Regenerate VEM Code Button',
    description: 'Button to generate fresh institutional VEM tracking number.',
    targetType: 'button',
    defaultAdmin: true,
    defaultUser: true,
  },
  {
    id: 'encode_due_override',
    page: 'Encode Letter',
    name: 'Manual SLA Due Date Override',
    description: 'Custom date picker to modify auto-computed SLA resolution target.',
    targetType: 'feature',
    defaultAdmin: true,
    defaultUser: true,
  },

  // Live Search Page
  {
    id: 'search_live',
    page: 'Live Search',
    name: 'Instant As-You-Type Search',
    description: 'Debounced full-text search querying metadata and OCR bodies.',
    targetType: 'feature',
    defaultAdmin: true,
    defaultUser: true,
  },
  {
    id: 'search_ctrlk',
    page: 'Live Search',
    name: 'Global Ctrl+K Command Palette',
    description: 'Universal keyboard modal accessible anywhere in the application.',
    targetType: 'feature',
    defaultAdmin: true,
    defaultUser: true,
  },

  // Settings & System Administration
  {
    id: 'settings_users',
    page: 'Settings',
    name: 'User Accounts Management',
    description: 'Create accounts, assign Administrator/Staff roles, and reset user passwords.',
    targetType: 'system',
    defaultAdmin: true,
    defaultUser: false,
  },
  {
    id: 'settings_self_password',
    page: 'Settings',
    name: 'Self Password Change',
    description: 'Allows current logged-in user to change their personal password.',
    targetType: 'feature',
    defaultAdmin: true,
    defaultUser: true,
  },
  {
    id: 'settings_format',
    page: 'Settings',
    name: 'Reference Format Customizer',
    description: 'Customize reference numbering prefix, separator, and digits padding.',
    targetType: 'system',
    defaultAdmin: true,
    defaultUser: false,
  },
  {
    id: 'settings_backup_export',
    page: 'Settings',
    name: 'Export Letters Backup (.json)',
    description: 'Download complete system snapshot of letters, attachments, and OCR texts.',
    targetType: 'system',
    defaultAdmin: true,
    defaultUser: false,
  },
  {
    id: 'settings_backup_restore',
    page: 'Settings',
    name: 'Restore Letters Backup (.json)',
    description: 'Upload previously saved JSON backup to restore repository records.',
    targetType: 'system',
    defaultAdmin: true,
    defaultUser: false,
  },
  {
    id: 'settings_wipe',
    page: 'Settings',
    name: 'Wipe / Clear Database Letters',
    description: 'Factory clear all registered letters or reload sample fixtures.',
    targetType: 'system',
    defaultAdmin: true,
    defaultUser: false,
  },
  {
    id: 'settings_matrix_edit',
    page: 'Settings',
    name: 'Modify Access Permissions Matrix',
    description: 'Administrative authority to toggle buttons and actions for all roles.',
    targetType: 'system',
    defaultAdmin: true,
    defaultUser: false,
  },
];

export function getDefaultPermissionsMap(): Record<string, { admin: boolean; user: boolean }> {
  const map: Record<string, { admin: boolean; user: boolean }> = {};
  for (const item of ALL_PERMISSIONS) {
    map[item.id] = {
      admin: item.defaultAdmin,
      user: item.defaultUser,
    };
  }
  return map;
}
